language: java
sudo: false
cache:
  directories:
  - "$HOME/.gradle/caches"
  - "$HOME/.gradle/wrapper"
notifications:
  email: false
  irc:
    channels:
      - secure: Rd4c9WhmrVR6PnvUlJG98iTwwPI7AskIfdfSmjiM5A2RlU1kMLhe8MzZsrDniJlWvG5FVJVnWKw5j2tLQXwwLfUj5LngVj3XKp62fuV7QT9RhfTSZ7piKWUtNHZz+zcujBf/AgONsHjMEJQ4/LDIwiQncPtaf8uDj9VEolvvUgJEuoy9gl+cARVqaD3C6v8/ZhoxcBsDfBDS0G+UBqDMzq/XuFnyQA5ztorXgryLFPpW2nHDjKlyNy/9SVx65Q84C+eblxovTf/PtAtZTPGEbEuc3Xuxbt+Oxcu1VPK4lVit3lgPxK8LeW4E9/naafjpjmUlVPaEdlWrqnYqY41HQShhyA0daTP6eBp8atPViyTVpo7+Vr2FoPWBulkJMHiP0TajBZSN++3D0EGCrzEKAyucYR2cetknkwIU35C19WqtaVFXQIZeeDyLDYdkAHXfacZ+cJLox1XoBxkbkmXXAu9WUEPLDptGv+7Po1ZiuVeybWeJD9B/a22hrDzYr2fsv5Z3XROapN670pHduNLqNBJl40Pob3+hZ5EHbRxrUWmJBFvewYZuSlatFWc/DHdT9pbph0b3LA/ImYE55K+o/Q3iVsPtXWvSKFkXz/E/o5F4x4NZGAVrwwT1UW1a9xdCvv+mAMoSTHHoknjDwgRjjODyEhV4tVUi4LMppMGF+0E=
    nick: travis-ci
    password:
      - secure: ZKa0uRsuMtCMefRkg66MU+5huA0PU1ka/8vMa8p2/UltTxm92AHFgoMQiM1ar49ToKUaoM7zXRrxPbpll+tLY+Hci4NqtR/EQBB3XxsglB00Q1Tp3K/GLeBbtZ6r0rUYsWvFKnhq88ysSnjpZAJ6PAt4EiWPntDYPv1aVhAlQIbjRWVwtIHNBgBjJMzGLz53KRfMK8Gi0rpr9HbZ3Q0UZwotVFE1vkNds6liMvtqitqj9A0mDpkqEE2uKJfYQTpTZCswei5u4mEQjJHnUcdm+xycDZ4JpCXHVHXP++yZWkNIPmef9+lMfeN71qxoIIAE20BBasmV1K7se8OrRVHRjQQKsvJdqcyQyu31Vct7CrPBWc1rRDIVCbVM96gAdNv1IOlPqLmROQovGzpc4r9K2AqCWHzsgSmd4fvuEuqk8QhDQaDWjxKwufeh+MpPVj9/dvsXBc2j2kle1rkslK8GeBVDZXa3p4NpoFAcPVAV2/Y1VpJVendCE/0MbS0W/CC36wOGsdBEt/svp+JTao9+ZEZDuBUNZ8pl/5+F0ONpOa5wiQXCvQfdw0NdxJWg/R6YNruByVYss5m7nr8398k4gh0cA1x1kTxLVPyFs1PuvmdCp2sWbQrxrsmmly8RcWg1I/0zMgNANJrCEP5Al7Rom/83kreJcIHnxHcY58ogmoU=
deploy:
  provider: releases
  api_key:
    secure: BsWoyVEdvAeXOiiUDRNlSHwZyCFZiikz1sTQAv6zPRQSJxR9i3WTPm+tEH2LvpoQIiYi+6JQJHKQ50xbo9KZ7fuExslAiY9gyJ9qwYsQpwRrd6dqwhHh1jrHslizFB6IWRJbBhKhT88EZBZuk4mOtdTcAbh+/qadj/7TY52gLGeCxwAV3CtBU5b0jPCL+I12BJMdvXx36iKGAFD3uJoO0jXUeCwdVE6WH5RtQ19pYfSEfE1AR/p5+HkR9CK0ZvuTtf3DDTX6OUfbiOmNTHBcwkpbqilPf/8+estNNgnHLUa2H9GQUahwN8UnU2kkg429/4W0LbutAlWh9bLbgOKA3veq05wPyqdTDHqCS4gLaBLW2IvlxT7HpfrT0cnWwF7kHoV2dKsrbjkizED6ZFsTVDucllr5U78xodcjaUNnqrTUT3pw31tuYNxt+WjKHYyJnNJ1APS8g9AxHz5QiNpz95r4WL/MWpiXKAFQaCSltGaxuLZa68G2HGIyZcfBtVwkaE4LXZhUK1aTdeJG4jdC6f7n7oi5Dcdq/kBTrUhc7JlC2rDFqCgaPx6SoQSa51EwG99MHzJSAgq+KQOXUtjd3d4+lQ5yBpk0nq9TS7kzPfPw259W2xe3xGNqB/7r+zFjbNkJteu9nP1lr4rQzs1oBTOcCkM9+pZNkmVf50J4OhI=
  file:
    - build/libs/TConstruct-1.7.10-*-GTNH.DEV.*.jar
    - build/libs/TConstruct-1.7.10-*-GTNH.DEV.*-deobf.jar
    - build/libs/TConstruct-1.7.10-*-GTNH.DEV.*-lib.jar
    - build/libs/TConstruct-1.7.10-*-GTNH.DEV.*-sources.jar
  file_glob: true
  skip_cleanup: true
  on:
    repo: GTNewHorizons/TinkersConstruct
    branch: 1.7.10
    tags: true
